import {emptyCity,loadCity,saveCity,validateCity,onReservedPath,defaultRoom,validateRoom,furnitureSizes} from './city-data.js';
const $=id=>document.getElementById(id),canvas=$('editorMap'),ctx=canvas.getContext('2d');
let base;try{base=JSON.parse(localStorage.getItem('mark-city-catalog-v1'));}catch{}
if(!Array.isArray(base)||!base.length){location.replace('index.html?openEditor=1'+(new URLSearchParams(location.search).has('room')?'&room='+Number(new URLSearchParams(location.search).get('room')):''));throw Error('Загрузка каталога города для редактора.');}
if(new URLSearchParams(location.search).has('room')){setupRoomEditor();}else{
let data=loadCity(),selected=0,mode='select',drag=null,history=[],dirty=false,profileId=0,houseDraft=false,replyDraft=false;
const roomLink=document.createElement('a');roomLink.textContent='Обустроить выбранный дом';roomLink.id='roomLink';document.querySelector('aside').appendChild(roomLink);roomLink.onclick=e=>{try{persist()}catch(error){e.preventDefault();say(error.message)}};
const all=()=>[...base.map((b,i)=>data.overrides[i]||b),...data.added];
const say=text=>$('status').textContent=text;
function remember(){history.push(JSON.stringify(data));if(history.length>30)history.shift();dirty=true;}
function assign(id,b){if(id<base.length)data.overrides[id]=b;else data.added[id-base.length]=b;}
function permitted(b,id=-1){if(data.trees.some(p=>Math.abs(p.x-b.x)<b.w/2+1.5&&Math.abs(p.z-b.z)<b.d/2+1.5))throw Error('Здесь посажено дерево. Оставь свободный проход.');if(onReservedPath(b.x,b.z,b.w,b.d))throw Error('Здесь дорога или тротуар. Выбери свободное место.');if(Math.abs(b.x)+b.w/2>86||Math.abs(b.z)+b.d/2>30)throw Error('Дом должен оставаться на карте.');if(all().some((other,i)=>i!==id&&Math.abs(other.x-b.x)<(other.w+b.w)/2+1&&Math.abs(other.z-b.z)<(other.d+b.d)/2+1))throw Error('Слишком близко к другому дому. Оставь проход.');}
function validatePlacement(candidate){const before=data;data=candidate;try{Object.entries(candidate.overrides).forEach(([i,b])=>{if(!base[i])throw Error('Неизвестный номер дома.');if(['x','z','w','d'].some(k=>b[k]!==base[i][k]))permitted(b,Number(i));});candidate.added.forEach((b,i)=>permitted(b,base.length+i));for(const p of candidate.trees)if(onReservedPath(p.x,p.z,.8,.8)||all().some(b=>Math.abs(p.x-b.x)<b.w/2+1.5&&Math.abs(p.z-b.z)<b.d/2+1.5))throw Error('Дерево закрывает проход.');}finally{data=before;}}
function fields(){$('roomLink').href=`editor.html?room=${selected}`;const b=all()[selected];if(!b)return;for(const k of ['name','x','z','w','d','h'])$(k).value=b[k];$('color').value='#'+b.color.toString(16).padStart(6,'0');$('buildingList').value=selected;}
function refresh(){const list=$('buildingList');list.replaceChildren();all().forEach((b,i)=>{const option=document.createElement('option');option.value=i;option.textContent=b.name;list.appendChild(option)});selected=Math.min(selected,all().length-1);fields();$('hello').value=data.profiles[profileId].hello;$('placeReply').value=data.profiles[profileId].place;draw();}
function draw(){ctx.fillStyle='#a2bf7d';ctx.fillRect(0,0,1080,420);const rect=(x,z,w,d,color)=>{ctx.fillStyle=color;ctx.fillRect((x-w/2+90)*6,(z-d/2+35)*6,w*6,d*6);};for(const z of [-17,17]){rect(0,z,160,9.5,'#e5d9b6');rect(0,z,160,7,'#9eaaa4');}for(const x of [-56,23])rect(x,0,7,41,'#9eaaa4');rect(6,0,2.5,24,'#6ebbc8');all().forEach((b,i)=>{rect(b.x,b.z,b.w,b.d,'#'+b.color.toString(16).padStart(6,'0'));if(i===selected){ctx.strokeStyle='#254f48';ctx.lineWidth=3;ctx.strokeRect((b.x-b.w/2+90)*6-2,(b.z-b.d/2+35)*6-2,b.w*6+4,b.d*6+4);}ctx.fillStyle='#243e39';ctx.font='10px system-ui';ctx.fillText(b.name.slice(0,10),(b.x-b.w/2+90)*6,(b.z+b.d/2+35)*6+11);});for(const p of data.trees){ctx.fillStyle='#367653';ctx.beginPath();ctx.arc((p.x+90)*6,(p.z+35)*6,7,0,Math.PI*2);ctx.fill();}}
const point=e=>{const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*180-90,z:(e.clientY-r.top)/r.height*70-35};};
canvas.onpointerdown=e=>{try{commitDrafts()}catch(error){say(error.message);return;}const p=point(e);if(mode==='tree'){try{if(onReservedPath(p.x,p.z,.8,.8)||all().some(b=>Math.abs(p.x-b.x)<b.w/2+1.5&&Math.abs(p.z-b.z)<b.d/2+1.5))throw Error('Дереву нужно свободное место, подальше от входов.');if(data.trees.length>=120)throw Error('Уже достаточно деревьев для лёгкой игры.');remember();data.trees.push(p);mode='select';draw();say('Дерево посажено. Нажми «Сохранить и гулять».');}catch(e){say(e.message)}return;}const hit=all().findIndex(b=>Math.abs(p.x-b.x)<b.w/2&&Math.abs(p.z-b.z)<b.d/2);if(hit>=0){selected=hit;fields();draw();drag={start:p,original:{...all()[hit]}};canvas.setPointerCapture(e.pointerId);}};
canvas.onpointermove=e=>{if(!drag)return;const p=point(e),b={...drag.original,x:Math.round((drag.original.x+p.x-drag.start.x)*2)/2,z:Math.round((drag.original.z+p.z-drag.start.z)*2)/2};$('x').value=b.x;$('z').value=b.z;houseDraft=true;dirty=true;};
canvas.onpointerup=()=>{if(!drag)return;drag=null;$('apply').click();};canvas.onpointercancel=()=>{drag=null;houseDraft=false;fields();};
$('buildingList').onchange=()=>{const next=Number($('buildingList').value);try{commitDrafts();selected=next;fields();draw();}catch(e){$('buildingList').value=selected;say(e.message)}};
function commitDrafts(){
 if(!houseDraft&&!replyDraft)return;
 const candidate=structuredClone(data);
 if(houseDraft){const b={...all()[selected],name:$('name').value,color:parseInt($('color').value.slice(1),16)};for(const k of ['x','z','w','d','h'])b[k]=Number($(k).value);if(selected<base.length)candidate.overrides[selected]=b;else candidate.added[selected-base.length]=b;validateCity(candidate);if(['x','z','w','d'].some(k=>b[k]!==all()[selected][k]))permitted(b,selected);}
 if(replyDraft)candidate.profiles[profileId]={...candidate.profiles[profileId],hello:$('hello').value,place:$('placeReply').value};
 validateCity(candidate);remember();data=candidate;houseDraft=false;replyDraft=false;refresh();
}
for(const id of ['name','x','z','w','d','h','color'])$(id).addEventListener('input',()=>{houseDraft=true;dirty=true;});
for(const id of ['hello','placeReply'])$(id).addEventListener('input',()=>{replyDraft=true;dirty=true;});
$('apply').onclick=()=>{try{commitDrafts();say('Дом и введённые правки применены.');}catch(e){say(e.message)}};
$('addHouse').onclick=()=>{try{commitDrafts();if(data.added.length>=60)throw Error('Достигнут предел новых домов.');let b=null;outer:for(let z=-8;z<=8;z+=6)for(let x=-45;x<=78;x+=7){const test={x,z,w:4,d:4,h:4,color:0xd5b2c9,name:'Новый дом',roof:true};try{permitted(test);b=test;break outer;}catch{}}if(!b)throw Error('Свободное место не найдено.');remember();data.added.push(b);selected=all().length-1;refresh();say('Новый дом добавлен. Выбери название и цвет.');}catch(e){say(e.message)}};
$('addTree').onclick=()=>{mode='tree';say('Нажми на свободное место на карте, чтобы посадить дерево.');};
$('saveReplies').onclick=()=>{try{commitDrafts();say('Реплики применены. После сохранения поговори с жителем.');}catch(e){say(e.message)}};
function persist(){commitDrafts();saveCity(data);dirty=false;say('Город сохранён в этом браузере.');}
$('save').onclick=()=>{try{persist()}catch(e){say('Не удалось сохранить: '+e.message)}};
$('playCity').onclick=e=>{try{persist()}catch(error){e.preventDefault();say(error.message)}};
$('undo').onclick=()=>{if(houseDraft||replyDraft){houseDraft=false;replyDraft=false;refresh();say('Ввод отменён.');return;}if(!history.length){say('Пока нечего отменять.');return;}data=JSON.parse(history.pop());dirty=true;refresh();say('Последнее изменение отменено. Нажми «Сохранить».');};
$('export').onclick=()=>{try{commitDrafts();const blob=new Blob([JSON.stringify(validateCity(data),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='мой-город.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Файл города скачан. Он содержит постройки, деревья и реплики.');}catch(e){say(e.message)}};
$('import').onchange=async()=>{const file=$('import').files[0];if(!file)return;try{if(file.size>1000000)throw Error('Файл слишком большой.');const candidate=validateCity(JSON.parse(await file.text()));validatePlacement(candidate);remember();data=candidate;houseDraft=false;replyDraft=false;refresh();say('Город загружен. Проверь карту и сохрани.');}catch(e){say('Не удалось загрузить: '+e.message)}$('import').value='';};
$('reset').onclick=()=>$('resetDialog').showModal();$('cancelReset').onclick=()=>$('resetDialog').close();$('confirmReset').onclick=()=>{remember();data=emptyCity();houseDraft=false;replyDraft=false;refresh();$('resetDialog').close();say('Исходный город восстановлен. Можно отменить или сохранить.');};
data.profiles.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.name;$('profileList').appendChild(o)});$('profileList').onchange=()=>{const next=Number($('profileList').value);try{commitDrafts();profileId=next;refresh();}catch(e){$('profileList').value=profileId;say(e.message)}};
addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});refresh();

}

function setupRoomEditor(){
 const data=loadCity(),id=Number(new URLSearchParams(location.search).get('room')),building=[...base.map((b,i)=>data.overrides[i]||b),...data.added][id];
 if(!building){location.replace('editor.html');return;}
 const original=()=>({...defaultRoom(),wall:building.color});let room=structuredClone(data.rooms[id]||original()),selected=0,history=[],dirty=false,draft=false;
 document.querySelector('h1').textContent='Обустроить: '+building.name;
 $('playCity').href=`index.html?home=${id}`;$('playCity').textContent='Сохранить и войти →';
 document.querySelector('main').innerHTML=`<section class="map-panel"><p>Комната сверху. Выбери мебель справа и нажми на свободное место, чтобы передвинуть её. Снизу — выход; проход к нему всегда остаётся свободным.</p><canvas id="roomMap" width="640" height="640" aria-label="План комнаты"></canvas><p id="status" role="status">Цвета и мебель сохраняются вместе с городом.</p><div class="tools"><button id="roomUndo">Отменить</button><button id="roomSave">Сохранить</button><button id="roomReset">Исходная комната</button><a href="editor.html">Весь город</a></div><dialog id="roomResetDialog"><p>Вернуть исходные цвета и мебель только этой комнаты?</p><button id="roomResetCancel">Отмена</button><button id="roomResetYes">Вернуть исходные</button></dialog></section><aside><label>Стены<input id="wallColor" type="color"></label><label>Пол<input id="floorColor" type="color"></label><h2>Мебель</h2><label>Предмет<select id="furnitureList"></select></label><label>X<input id="fx" type="number" step=".5"></label><label>Z<input id="fz" type="number" step=".5"></label><label>Цвет мебели<input id="fcolor" type="color"></label><button id="moveFurniture">Применить</button><label>Добавить<select id="furnitureType"><option value="sofa">Диван</option><option value="table">Стол</option><option value="cabinet">Шкаф</option></select></label><button id="addFurniture">＋ Предмет</button><button id="removeFurniture">Убрать выбранный</button></aside>`;
 const names={sofa:'Диван',table:'Стол',cabinet:'Шкаф'},canvas=$('roomMap'),ctx=canvas.getContext('2d'),hex=n=>'#'+n.toString(16).padStart(6,'0'),say=text=>$('status').textContent=text;
 const remember=()=>{history.push(structuredClone(room));if(history.length>30)history.shift();dirty=true;};
 function refresh(){const list=$('furnitureList');list.replaceChildren();room.furniture.forEach((f,i)=>{const option=document.createElement('option');option.value=i;option.textContent=names[f.type]+' '+(i+1);list.appendChild(option)});selected=Math.max(0,Math.min(selected,room.furniture.length-1));list.value=selected;const f=room.furniture[selected];$('fx').value=f?.x??0;$('fz').value=f?.z??0;$('fcolor').value=hex(f?.color??0xaaaaaa);$('wallColor').value=hex(room.wall);$('floorColor').value=hex(room.floor);ctx.fillStyle=hex(room.wall);ctx.fillRect(0,0,640,640);ctx.fillStyle=hex(room.floor);ctx.fillRect(16,16,608,608);ctx.fillStyle='#d9eae4';ctx.fillRect(248,440,144,184);ctx.fillStyle='#367d94';ctx.fillRect(268,618,104,10);ctx.font='16px sans-serif';ctx.fillText('ВЫХОД',289,604);room.furniture.forEach((f,i)=>{const size=furnitureSizes[f.type];ctx.fillStyle=hex(f.color);ctx.fillRect((f.x-size.w/2+8)*40,(f.z-size.d/2+8)*40,size.w*40,size.d*40);if(i===selected){ctx.strokeStyle='#294438';ctx.lineWidth=3;ctx.strokeRect((f.x-size.w/2+8)*40,(f.z-size.d/2+8)*40,size.w*40,size.d*40);}});}
 function commit(){if(!draft)return;const next=structuredClone(room),f=next.furniture[selected];if(!f){draft=false;return;}f.x=Number($('fx').value);f.z=Number($('fz').value);f.color=parseInt($('fcolor').value.slice(1),16);validateRoom(next);remember();room=next;draft=false;refresh();}
 for(const key of ['fx','fz','fcolor'])$(key).oninput=()=>{draft=true;dirty=true;};
 for(const [key,prop] of [['wallColor','wall'],['floorColor','floor']])$(key).oninput=()=>{const value=parseInt($(key).value.slice(1),16);try{commit();remember();room[prop]=value;refresh();}catch(e){say(e.message)}};
 $('furnitureList').onchange=()=>{const next=Number($('furnitureList').value);try{commit();selected=next;refresh();}catch(e){say(e.message)}};
 $('moveFurniture').onclick=()=>{try{commit();say('Мебель переставлена.')}catch(e){say(e.message)}};
 canvas.onclick=e=>{const r=canvas.getBoundingClientRect();$('fx').value=Math.round(((e.clientX-r.left)/r.width*16-8)*2)/2;$('fz').value=Math.round(((e.clientY-r.top)/r.height*16-8)*2)/2;draft=true;$('moveFurniture').click();};
 $('addFurniture').onclick=()=>{try{commit();if(room.furniture.length>=12)throw Error('В комнате уже 12 предметов.');let next=null;outer:for(let z=-5;z<=2;z+=2)for(let x=-5;x<=5;x+=2){const candidate=structuredClone(room);candidate.furniture.push({type:$('furnitureType').value,x,z,color:0x91aaa0});try{validateRoom(candidate);next=candidate;break outer;}catch{}}if(!next)throw Error('Свободное место не найдено.');remember();room=next;selected=room.furniture.length-1;refresh();}catch(e){say(e.message)}};
 $('removeFurniture').onclick=()=>{if(!room.furniture.length)return;remember();room.furniture.splice(selected,1);draft=false;refresh();};
 const save=()=>{commit();data.rooms[id]=validateRoom(room);saveCity(data);dirty=false;say('Комната сохранена.');};$('roomSave').onclick=()=>{try{save()}catch(e){say(e.message)}};$('playCity').onclick=e=>{try{save()}catch(error){e.preventDefault();say(error.message)}};
 $('roomUndo').onclick=()=>{if(draft){draft=false;refresh();return;}if(history.length){room=history.pop();dirty=true;refresh();say('Изменение отменено.');}};
 $('roomReset').onclick=()=>$('roomResetDialog').showModal();$('roomResetCancel').onclick=()=>$('roomResetDialog').close();$('roomResetYes').onclick=()=>{remember();room=original();draft=false;refresh();$('roomResetDialog').close();};
 addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});refresh();
}
