import {setupEpisodes} from '../comics/episodes.js';
import {setupFamily} from '../comics/family.js';
import {make3DCity} from './scene.js';
import {setupConcert,drawConcert} from '../comics/concert.js';
import {CHAPTERS,TOTAL,currentMission,checkAnswer,loadProgress,saveProgress} from '../comics/adventure.js';
import {WORLD_WIDTH,GROUND,MAP_KEY,defaultMap,validateMap,loadMap,stepHero,jumpHero} from '../comics/world.js';
const $=id=>document.getElementById(id),canvas=$('world'),ctx=document.createElement('canvas').getContext('2d');
let storage;try{storage=localStorage;}catch{storage={getItem(){return null},setItem(){throw Error('Storage unavailable')}};}
let world=loadMap(storage),chapter=loadProgress(storage),active=false,time=0,last=0,cam=0,viewW=1400,viewH=820,scale=1,offsetY=0;
let weather=0,day=0,autoTime=false,cycleTime=0,sparks=0,attack=0,attackCooldown=0,dash=0,dashCooldown=0,invulnerable=0,toastTime=0,shake=0;
const keys=new Set(),hero={x:260,y:GROUND,vy:0,speed:310,jumps:0,grounded:true,face:1,z:0},particles=[],bursts=[];
const city3d=make3DCity(canvas,()=>world);
canvas.addEventListener('wheel',e=>{e.preventDefault();city3d.distance=Math.max(7,Math.min(22,city3d.distance+e.deltaY*.012));},{passive:false});
let yaw=-.55,drag=null;canvas.addEventListener('pointerdown',e=>{if(!active)return;drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-drag.x)*.005;city3d.pitch=Math.max(.1,Math.min(.9,city3d.pitch+(e.clientY-drag.y)*.003));drag={x:e.clientX,y:e.clientY};});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>drag=null);
const sky=new Image(),sprites=new Image();sky.src='../comics/assets/neighborhood.png';sprites.src='../comics/assets/mark-baseball.png?v=3';
for(const img of [sky,sprites])img.onerror=()=>{$('error').hidden=false;$('error').textContent='An illustration could not load. Reload the page to try again.';};
const friendLines={Veronika:'We’re in different classes, but art club is our thing! I swapped the paint labels. Can you solve my color puzzle in Friends & family?',Abir:'Hey Mark! Let’s think it through together. I’ll help you test every clue. Ready for the school mission?',Koki:'Race you to the next rooftop! At the baseball park, let’s read the scoreboard before guessing.',Egor:'Hey little brother! Josie and I are cheering for you. I’m 24, and I still use maths to plan shopping and meals.',Josie:'Welcome to the library! Egor and I found a secret code on the Dog Man shelf. Read carefully — every clue matters.'};
const companions=[{name:'Veronika',district:0,offset:160,skin:'#e6bb96',shirt:'#dd86a7',hair:'#7d5a3b'},{name:'Abir',district:0,offset:-135,skin:'#ac784f',shirt:'#188d88',hair:'#242535'},{name:'Koki',district:3,offset:-125,skin:'#dcb186',shirt:'#eaa837',hair:'#483222'},{name:'Egor',district:2,offset:-135,skin:'#dfb88f',shirt:'#34566f',hair:'#302932',adult:true},{name:'Josie',district:4,offset:-135,skin:'#d3a682',shirt:'#9454a4',hair:'#201c29',adult:true,longHair:true}];
setupConcert({$,pause,resume,travel:()=>{hero.x=8270;hero.z=0;hero.y=GROUND;hero.vy=0;cam= Math.max(0,WORLD_WIDTH-viewW);},reward:()=>{sparks+=30;}});
setupFamily({pause,resume,hint:()=>currentMission(chapter)?.puzzles[chapter%3].hint||'You solved every clue! Now you can build your own map.'});
setupEpisodes({pause,resume});
const drones=Array.from({length:22},(_,i)=>({x:600+i*390,origin:600+i*390,y:GROUND-60-(i%3)*80,alive:true,phase:i,respawn:0}));
let coins=[];function resetCoins(){coins=world.platforms.flatMap((p,i)=>Array.from({length:3},(_,j)=>({x:p.x+30+j*(p.w-60)/2,y:p.y-42,taken:false,seed:i+j})));}resetCoins();
function resize(){const dpr=Math.min(devicePixelRatio||1,2);city3d.resize();canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';scale=Math.max(.55,Math.min(innerHeight/820,innerWidth/900));viewW=innerWidth/scale;viewH=innerHeight/scale;offsetY=Math.max(0,viewH-820)*.5;}resize();addEventListener('resize',resize);
function showToast(text){$('comicToast').textContent=text;$('comicToast').hidden=false;toastTime=4;}
function currentDistrict(){return world.districts[Math.min(5,Math.floor(chapter/3))];}
function nearMission(){return chapter<TOTAL&&Math.abs(hero.x-currentDistrict().x)<110&&Math.abs(hero.z)<100&&hero.y>GROUND-120;}
function pause(){active=false;keys.clear();}
function resume(){active=true;keys.clear();}
function burst(text,x,y,color='#ffd05c'){bursts.push({text,x,y,life:1,color});}
function splash(x,y,color,count=16){for(let i=0;i<count;i++){const a=i/count*Math.PI*2;particles.push({x,y,vx:Math.cos(a)*(90+Math.random()*150),vy:Math.sin(a)*170-90,life:.5+Math.random()*.5,color});}}
function jump(){if(!active)return;if(jumpHero(hero)){splash(hero.x,hero.y,'#ffdd75',7);if(hero.jumps===2)burst('UP!',hero.x,hero.y-100);}}
function doDash(){if(!active||dashCooldown>0)return;dash=.23;dashCooldown=1.4;burst('WHOOSH!',hero.x,hero.y-115,'#7de9e0');}
function blast(){if(!active||attackCooldown>0)return;attack=.27;attackCooldown=.42;shake=4;splash(hero.x+hero.face*70,hero.y-65,'#64e1dc');burst('SPLASH!',hero.x+hero.face*90,hero.y-145);for(const drone of drones){if(drone.alive&&Math.abs(drone.x-(hero.x+hero.face*80))<180&&Math.abs(drone.y-(hero.y-60))<145){drone.alive=false;drone.respawn=20;sparks+=5;splash(drone.x,drone.y,'#e782ed',22);}}}
function interact(){if(!active)return;if(nearMission()){openPuzzle();return;}const friend=companions.find(f=>Math.abs(hero.x-(world.districts[f.district].x+f.offset))<110);if(friend)showToast(friend.name+': '+friendLines[friend.name]);}
addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.code==='Escape'){if(!document.querySelector('dialog[open]')){pause();$('welcome').showModal();e.preventDefault();}return;}if(!active)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);const turn={KeyW:Math.PI,ArrowUp:Math.PI,KeyS:0,ArrowDown:0,KeyD:Math.PI/2,ArrowRight:Math.PI/2,KeyA:-Math.PI/2,ArrowLeft:-Math.PI/2}[e.code];if(turn!==undefined)hero.heading=yaw+turn;if(!e.repeat){if(e.code==='Space')jump();if(e.code==='KeyF')blast();if(e.code==='KeyE')interact();if(e.code==='ShiftLeft'||e.code==='ShiftRight')doDash();if(e.code==='KeyR')home();}});
addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{keys.clear();last=0;});
for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();if(active)keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);};for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.key));}
$('touchJump').onclick=jump;$('touchDash').onclick=doDash;$('power').onclick=blast;$('interact').onclick=interact;
function home(){hero.x=260;hero.z=0;hero.y=GROUND;hero.vy=0;hero.jumps=0;keys.clear();}
$('home').onclick=home;$('play').onclick=()=>{$('welcome').close();resume();};$('menuButton').onclick=()=>{pause();$('welcome').showModal();};$('welcome').addEventListener('cancel',resume);$('welcome').showModal();
$('timeButton').onclick=()=>{day=(day+1)%3;cycleTime=0;updateEnvironment();};$('weatherButton').onclick=()=>{weather=(weather+1)%4;updateEnvironment();};$('autoTime').onclick=()=>{autoTime=!autoTime;updateEnvironment();};
function updateEnvironment(){$('timeButton').textContent=['☀ Day','◒ Sunset','☾ Night'][day];$('weatherButton').textContent=['Clear sky','Cloudy','Rain','Snow'][weather];$('autoTime').textContent='Auto time: '+(autoTime?'on':'off');}
$('travel').onclick=()=>{if(chapter>=TOTAL)return;const d=currentDistrict();hero.x=d.x-75;hero.z=0;hero.y=GROUND;hero.vy=0;hero.jumps=0;keys.clear();cam=Math.max(0,Math.min(WORLD_WIDTH-viewW,hero.x-viewW*.4));showToast(d.name+' — press E to solve the clue.');};
function refreshQuest(){const c=currentMission(chapter);$('questNumber').textContent=c?`PAGE 0${Math.floor(chapter/3)+1} / 06`:'ISSUE COMPLETE';$('questTitle').textContent=c?c.title:'You saved the colors!';$('questText').textContent=c?`${c.friend} is waiting. ${chapter%3} / 3 clues solved. Follow the golden sketchbook.`:'All 18 clues solved! Keep exploring, remix the map, or replay the issue.';$('questProgress').style.width=`${chapter/TOTAL*100}%`;$('questPlace').textContent=c?currentDistrict().name:'The Color Keepers';$('replayQuest').hidden=!!c;$('travel').hidden=!c;}
$('replayQuest').onclick=()=>{chapter=0;saveProgress(storage,chapter);refreshQuest();};
let puzzleSolved=false;
function closePuzzle(){window.speechSynthesis?.cancel();$('puzzle').close();resume();}
function openPuzzle(){const c=currentMission(chapter);if(!c)return;pause();puzzleSolved=false;const puzzle=c.puzzles[chapter%3];$('puzzleSkill').textContent=`${puzzle.skill} · ${chapter%3+1}/3`;$('puzzleTitle').textContent=puzzle.title;$('puzzleArt').textContent=puzzle.art;$('puzzleQuestion').textContent=puzzle.question;$('feedback').textContent='Take your time. You can always ask for a hint.';$('nextPuzzle').hidden=true;$('hintButton').disabled=false;$('answers').replaceChildren();puzzle.answers.forEach((answer,index)=>{const button=document.createElement('button');button.textContent=String.fromCharCode(65+index)+'. '+answer;button.onclick=()=>{if(puzzleSolved)return;if(checkAnswer(puzzle,index)){puzzleSolved=true;button.classList.add('correct');$('feedback').textContent='Exactly! '+puzzle.explanation;chapter++;sparks+=10;if(!saveProgress(storage,chapter))$('feedback').textContent+=' Progress could not be saved in this browser.';refreshQuest();$('nextPuzzle').hidden=false;$('nextPuzzle').textContent=chapter===TOTAL?'Finish the issue ★':chapter%3===0?'Page restored! Back to the city →':'Next clue →';$('hintButton').disabled=true;for(const b of $('answers').children)b.disabled=true;}else{button.classList.add('incorrect');button.disabled=true;$('feedback').textContent='Not quite yet. '+puzzle.hint;}};$('answers').appendChild(button);});$('hintButton').onclick=()=>{$('feedback').textContent='Abir: '+puzzle.hint;};$('readButton').disabled=!('speechSynthesis' in window);$('readButton').onclick=()=>{window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(puzzle.title+'. '+puzzle.question+'. '+puzzle.answers.map((a,i)=>String.fromCharCode(65+i)+': '+a).join('. '));speech.lang='en-US';speech.rate=.9;window.speechSynthesis.speak(speech);};if(!$('puzzle').open)$('puzzle').showModal();}
$('closePuzzle').onclick=closePuzzle;$('puzzle').addEventListener('cancel',()=>{window.speechSynthesis?.cancel();resume();});$('nextPuzzle').onclick=()=>{window.speechSynthesis?.cancel();if(chapter%3===0){closePuzzle();splash(hero.x,hero.y-100,'#ffcd52',35);showToast(chapter===TOTAL?'KAPOW! 18 clues solved. The city is yours!':'PAGE RESTORED! The next neighborhood is ready.');}else openPuzzle();};
$('journalButton').onclick=()=>{pause();$('chapters').replaceChildren();CHAPTERS.forEach((c,i)=>{const card=document.createElement('article');card.className='chapter-card'+(chapter>=(i+1)*3?' done':Math.floor(chapter/3)===i?' current':'');const tag=document.createElement('small');tag.textContent=`PAGE 0${i+1} · ${chapter>=(i+1)*3?'RESTORED':Math.floor(chapter/3)===i?'IN PROGRESS':'UP NEXT'}`;const title=document.createElement('h3');title.textContent=world.districts[i].name;const desc=document.createElement('p');desc.textContent=c.friend+' · '+c.puzzles.map(p=>p.skill.split(' · ')[0].toLowerCase()).join(', ');card.append(tag,title,desc);$('chapters').appendChild(card);});$('journal').showModal();};$('closeJournal').onclick=()=>{$('journal').close();resume();};$('journal').addEventListener('cancel',resume);
// The map editor operates on a validated draft; closing discards unsaved changes.
let draft=null,history=[],dragDistrict=-1;
const editor=$('editMap'),ec=editor.getContext('2d');
function remember(){history.push(structuredClone(draft));if(history.length>40)history.shift();}
function showFields(){const d=draft.districts[Number($('districtSelect').value)||0];$('districtName').value=d.name;$('districtX').value=Math.round(d.x);drawEditor();}
function drawEditor(){ec.fillStyle='#182239';ec.fillRect(0,0,900,220);ec.strokeStyle='#53617a';for(let i=0;i<=9;i++){ec.beginPath();ec.moveTo(i*100,20);ec.lineTo(i*100,190);ec.stroke();ec.fillStyle='#bec9d9';ec.font='10px Arial';ec.fillText(i*1000,i*100+3,211);}for(const p of draft.platforms){ec.fillStyle='#88c6ce';ec.fillRect(p.x/10,50+(p.y-300)*.36,p.w/10,5);}draft.districts.forEach((d,i)=>{const x=d.x/10;ec.fillStyle=Number($('districtSelect').value)===i?'#ef4057':'#ffd05c';ec.beginPath();ec.arc(x,32,13,0,7);ec.fill();ec.fillStyle='#182239';ec.font='bold 12px Arial';ec.textAlign='center';ec.fillText(i+1,x,36);ec.textAlign='left';});}
$('workshopButton').onclick=()=>{pause();draft=structuredClone(world);history=[];$('districtSelect').replaceChildren();draft.districts.forEach((d,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${i+1}. ${d.name}`;$('districtSelect').appendChild(o);});$('mapFeedback').textContent='Drag numbered circles, or use the fields. Save when ready.';showFields();$('mapWorkshop').showModal();};$('districtSelect').onchange=showFields;
function editMap(change){try{const next=structuredClone(draft);change(next);validateMap(next);remember();draft=next;showFields();$('mapFeedback').textContent='Draft updated. Save & play to use it.';}catch(e){$('mapFeedback').textContent=e.message;}}
$('applyDistrict').onclick=()=>editMap(m=>{m.districts[Number($('districtSelect').value)]={name:$('districtName').value,x:Number($('districtX').value)};});$('addPlatform').onclick=()=>editMap(m=>m.platforms.push({x:Number($('platformX').value),y:Number($('platformY').value),w:180}));$('undoMap').onclick=()=>{if(history.length){draft=history.pop();showFields();$('mapFeedback').textContent='Undid the last draft change.';}};
editor.onpointerdown=e=>{const rect=editor.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*900,y=(e.clientY-rect.top)/rect.height*220;dragDistrict=draft.districts.findIndex(d=>Math.hypot(d.x/10-x,32-y)<22);if(dragDistrict>=0){remember();$('districtSelect').value=dragDistrict;editor.setPointerCapture(e.pointerId);}};editor.onpointermove=e=>{if(dragDistrict<0)return;const rect=editor.getBoundingClientRect();draft.districts[dragDistrict].x=Math.round(Math.max(250,Math.min(8750,(e.clientX-rect.left)/rect.width*9000)));showFields();};editor.onpointerup=()=>{if(dragDistrict<0)return;dragDistrict=-1;try{validateMap(draft);$('mapFeedback').textContent='District moved. Save to apply.';}catch(e){draft=history.pop();showFields();$('mapFeedback').textContent=e.message;}};editor.onpointercancel=()=>{if(dragDistrict>=0){dragDistrict=-1;draft=history.pop();showFields();}};
$('saveMap').onclick=()=>{try{const clean=validateMap(draft);storage.setItem(MAP_KEY,JSON.stringify(clean));world=clean;city3d.rebuild();resetCoins();refreshQuest();$('mapWorkshop').close();resume();showToast('Your map is saved in this browser.');}catch(e){$('mapFeedback').textContent='Could not save: '+e.message+' You can export your draft.';}};
$('exportMap').onclick=()=>{try{const clean=validateMap(draft),url=URL.createObjectURL(new Blob([JSON.stringify(clean,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='mark-city-map.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('mapFeedback').textContent='Map exported. Import it in another browser to continue building.';}catch(e){$('mapFeedback').textContent=e.message;}};
$('importMap').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>100000)throw Error('Map file must be under 100 KB.');const next=validateMap(JSON.parse(await file.text()));remember();draft=next;showFields();$('mapFeedback').textContent='Map imported into your draft. Save & play to apply.';}catch(error){$('mapFeedback').textContent='Could not import: '+error.message;}e.target.value='';};
$('resetMap').onclick=()=>{remember();draft=defaultMap();showFields();$('mapFeedback').textContent='Default map loaded into draft. Undo restores your draft; Save applies it.';};$('closeWorkshop').onclick=()=>{$('mapWorkshop').close();resume();};$('mapWorkshop').addEventListener('cancel',resume);
// Rendering: painted environment, sprite animation, parallax, weather and comic VFX.
function ellipse(x,y,rx,ry,fill,stroke){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=3;ctx.stroke();}}
function panel(text,x,y,color='#fff1d2',size=16){ctx.font=`900 ${size}px Arial`;const w=ctx.measureText(text).width+26;ctx.fillStyle='#172238';ctx.fillRect(x-w/2+4,y+4,w,32);ctx.fillStyle=color;ctx.fillRect(x-w/2,y,w,32);ctx.strokeStyle='#182239';ctx.lineWidth=2;ctx.strokeRect(x-w/2,y,w,32);ctx.fillStyle='#182239';ctx.textAlign='center';ctx.fillText(text,x,y+22);ctx.textAlign='left';}
function drawFriend(f){const x=world.districts[f.district].x+f.offset+(f.name==='Egor'?Math.sin(time*.6)*65:0),y=GROUND-(f.name==='Egor'?12:0),sz=f.adult?1.12:.93;ctx.save();ctx.translate(x,y);ctx.scale(sz,sz);const ink='#1a2339';ctx.lineCap='round';ctx.lineWidth=15;ctx.strokeStyle=ink;for(const a of [-1,1]){ctx.beginPath();ctx.moveTo(a*9,-42);ctx.lineTo(a*12,-9);ctx.stroke();ellipse(a*13,-5,13,6,'#f6efd7',ink);}ctx.fillStyle=f.shirt;ctx.strokeStyle=ink;ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(-20,-89,40,51,10);ctx.fill();ctx.stroke();ctx.strokeStyle=f.skin;ctx.lineWidth=11;for(const a of [-1,1]){ctx.beginPath();ctx.moveTo(a*22,-79);ctx.lineTo(a*28,-49+Math.sin(time*2)*3);ctx.stroke();}if(f.longHair)ellipse(0,-100,29,37,f.hair,ink);ellipse(0,-110,25,28,f.skin,ink);ctx.fillStyle=f.hair;ctx.beginPath();ctx.moveTo(-25,-116);ctx.quadraticCurveTo(-29,-147,10,-142);ctx.quadraticCurveTo(29,-139,27,-113);ctx.lineTo(10,-127);ctx.lineTo(-5,-121);ctx.lineTo(-12,-130);ctx.closePath();ctx.fill();for(const a of [-1,1]){ellipse(a*9,-111,4,5,'#fff');ellipse(a*9+1,-110,2,3,ink);}ctx.strokeStyle=ink;ctx.lineWidth=2;ctx.beginPath();ctx.arc(1,-100,7,.2,2.7);ctx.stroke();ctx.restore();if(f.name==='Egor'){ctx.strokeStyle='#20304b';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(x-33,GROUND-10);ctx.quadraticCurveTo(x,GROUND-3,x+33,GROUND-10);ctx.stroke();ellipse(x-20,GROUND-2,5,5,'#f0be4f','#172239');ellipse(x+20,GROUND-2,5,5,'#f0be4f','#172239');}panel(f.name,x,y-175,'#fff1d2',13);}
function drawFamilyCar(){const x=world.districts[4].x+120+Math.sin(time*.14)*270,y=GROUND+50;ctx.save();ctx.translate(x,y);ctx.fillStyle='#ed777e';ctx.strokeStyle='#182239';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(-80,-60,160,47,15);ctx.fill();ctx.stroke();ctx.fillStyle='#aee4e2';ctx.beginPath();ctx.roundRect(-50,-98,103,52,18);ctx.fill();ctx.stroke();for(const [px,hair,skin] of [[-24,'#302536','#d3a682'],[23,'#c5c5ce','#e2bd9b']]){ellipse(px,-73,13,16,skin,'#182239');ctx.fillStyle=hair;ctx.beginPath();ctx.arc(px,-80,14,Math.PI,0);ctx.fill();ctx.fillStyle='#182239';ctx.fillRect(px-6,-74,3,3);ctx.fillRect(px+4,-74,3,3);}for(const px of [-50,50]){ellipse(px,-13,18,18,'#172339','#fff0c9');ellipse(px,-13,7,7,'#a5c1d2');}ellipse(72,-40,7,6,'#fff1ae');panel('JOSIE + GRANDMA',0,-135,'#ffe5b2',10);ctx.restore();}
function drawHero(){ctx.save();ctx.translate(hero.x,hero.y);ctx.scale(hero.face,1);if(invulnerable>0&&Math.floor(time*12)%2===0)ctx.globalAlpha=.55;let pose=!hero.grounded?3:Math.abs(moveDirection)>0?(Math.floor(time*9)%2)+1:0;if(dash>0)pose=3;if(sprites.complete&&sprites.naturalWidth){const cellW=sprites.naturalWidth/2,cellH=sprites.naturalHeight/2;const drawSize=177;ctx.drawImage(sprites,(pose%2)*cellW,Math.floor(pose/2)*cellH,cellW,cellH,-drawSize/2,-drawSize+9,drawSize,drawSize);}else{ellipse(0,-65,23,60,'#2d78dd','#182239');ellipse(0,-128,25,25,'#efc699','#182239');}ctx.restore();}
function drawDrone(d){ctx.save();ctx.translate(d.x,d.y);const colors=['#58d9ce','#ffcf66','#d6a2f3','#ff9c9a'];const c=colors[d.phase%colors.length];ellipse(0,0,25+Math.sin(time*2+d.phase)*2,28,c,'#fff2cc');ellipse(-7,-9,7,10,'#ffffff88');ctx.fillStyle='#fff9e9';ctx.font='bold 20px Arial';ctx.textAlign='center';ctx.fillText('✦',0,8);ctx.restore();}
let moveDirection=0;
function update(dt){time+=dt;attack=Math.max(0,attack-dt);attackCooldown=Math.max(0,attackCooldown-dt);dash=Math.max(0,dash-dt);dashCooldown=Math.max(0,dashCooldown-dt);invulnerable=Math.max(0,invulnerable-dt);toastTime=Math.max(0,toastTime-dt);shake=Math.max(0,shake-dt*30);const forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0),side=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);const len=Math.max(1,Math.hypot(forward,side));let dx=(side*Math.cos(yaw)-forward*Math.sin(yaw))/len,dz=(-forward*Math.cos(yaw)-side*Math.sin(yaw))/len;if(dx||dz){hero.face=dx<0?-1:1;hero.heading=Math.atan2(dx,dz);}moveDirection=Math.hypot(dx,dz);hero.speed=dash>0?850:230;if(dash>0){dx=Math.sin(hero.heading||0);dz=Math.cos(hero.heading||0);}const oldX=hero.x;stepHero(hero,dt,dx,Math.abs(hero.z)<22?world.platforms:[]);if(city3d.blocked(hero.x/10,hero.z/10))hero.x=oldX;const nextZ=Math.max(-600,Math.min(600,hero.z+dz*hero.speed*dt));if(!city3d.blocked(hero.x/10,nextZ/10))hero.z=nextZ;if(dash>0)splash(hero.x-hero.face*40,hero.y-35,'#a2e5ef',1);for(const c of coins){if(!c.taken&&Math.hypot(hero.x-c.x,hero.y-70-c.y)<65){c.taken=true;sparks++;splash(c.x,c.y,'#ffdb6c',5);}}for(const d of drones){if(!d.alive){d.respawn-=dt;if(d.respawn<=0)d.alive=true;continue;}d.x=d.origin+Math.sin(time*.6+d.phase)*95;d.y=GROUND-70-(d.phase%3)*80+Math.sin(time*2+d.phase)*20;if(Math.hypot(hero.x-d.x,hero.y-65-d.y)<65){d.alive=false;d.respawn=25;sparks+=5;burst('+5',d.x,d.y,'#a8eadb');splash(d.x,d.y,'#80e0cd',15);}}for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=400*dt;}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(const b of bursts){b.life-=dt;b.y-=dt*30;}for(let i=bursts.length-1;i>=0;i--)if(bursts[i].life<=0)bursts.splice(i,1);if(autoTime){cycleTime+=dt;if(cycleTime>=90){cycleTime=0;day=(day+1)%3;updateEnvironment();}}cam+=(Math.max(0,Math.min(Math.max(0,WORLD_WIDTH-viewW),hero.x-viewW*.38))-cam)*Math.min(1,dt*6);}
function render(){city3d.render({hero,time,day,weather,yaw,chapter,active,attack,moveDirection,companions,coins,drones});const c=currentDistrict();$('questDistance').textContent=chapter<TOTAL?Math.round(Math.hypot(hero.x-c.x,hero.z)/10)+' m':'18 / 18';$('comicToast').hidden=toastTime<=0;const friendNearby=companions.some(f=>Math.hypot(hero.x-world.districts[f.district].x-f.offset,hero.z)<140);$('interact').hidden=!active||(!nearMission()&&!friendNearby);$('interact').textContent=nearMission()?'Solve clue · E':'Talk to friend · E';$('paintScore').textContent='✦ '+sparks+' sparks';$('dashStatus').textContent=dashCooldown>0?'DASH '+dashCooldown.toFixed(1)+'s':'DASH READY';drawMinimap();}
function drawMinimap(){const m=$('map').getContext('2d');m.fillStyle='#182239';m.fillRect(0,0,320,120);m.strokeStyle='#78939e';m.lineWidth=2;for(const z of [0,-450,450]){m.beginPath();m.moveTo(12,66+z*.06);m.lineTo(308,66+z*.06);m.stroke();}for(let x=90;x<9000;x+=1300){const px=12+x/WORLD_WIDTH*296;m.beginPath();m.moveTo(px,39);m.lineTo(px,93);m.stroke();}world.districts.forEach((d,i)=>{m.fillStyle=chapter>=(i+1)*3?'#91d9ad':Math.floor(chapter/3)===i?'#ffd05c':'#889bb1';m.beginPath();m.arc(12+d.x/WORLD_WIDTH*296,66,4,0,7);m.fill();m.font='9px Arial';m.fillText(i+1,9+d.x/WORLD_WIDTH*296,57);});m.save();m.translate(12+hero.x/WORLD_WIDTH*296,66+hero.z*.06);m.rotate(-(hero.heading||0));m.fillStyle='#ff858e';m.beginPath();m.moveTo(0,5);m.lineTo(-4,-4);m.lineTo(4,-4);m.closePath();m.fill();m.restore();m.fillStyle='#e9dfc7';m.font='bold 9px Arial';m.fillText('MARK CITY / STREETS & GARDENS',12,22);m.font='8px Arial';m.fillText('SIDE LANES LEAD TO THE GARDENS',12,111);}
function frame(stamp){const dt=last?Math.min((stamp-last)/1000,.033):0;last=stamp;if(active)update(dt);render();requestAnimationFrame(frame);}refreshQuest();requestAnimationFrame(frame);
// Read-only diagnostics used during local development.
window.gameState=()=>({hero:{...hero},chapter,sparks,day,weather,autoTime,active,map:world,cam,dronesCleared:drones.filter(d=>!d.alive).length});
