import {residentProfiles} from './dialogues.js?v=school-5';
export const STORAGE_KEY='mark-next-city-edits-v1';
export const emptyCity=()=>({version:1,graffiti:null,rooms:{},overrides:{},added:[],trees:[],profiles:residentProfiles.map(p=>({...p})),replies:{hello:'Привет! Хорошего тебе дня и приятной прогулки!',place:'Возле школы, у воды, есть деревья и лавка. В любой дом можно войти у двери.'}});
export function validateCity(data){
 if(!data||data.version!==1||!data.overrides||typeof data.overrides!=='object'||Array.isArray(data.overrides)||!Array.isArray(data.added)||!Array.isArray(data.trees)||!data.replies)throw Error('Это не файл города версии 1.');
 if(Object.keys(data.overrides).length>160||data.added.length>60||data.trees.length>120)throw Error('Слишком много объектов для лёгкой игры.');
 const check=b=>{for(const k of ['x','z','w','d','h','color'])if(!Number.isFinite(b[k]))throw Error('Неверные размеры или координаты.');if(Math.abs(b.x)>82||Math.abs(b.z)>28||b.w<2||b.w>14||b.d<2||b.d>12||b.h<2||b.h>20||b.color<0||b.color>0xffffff||typeof b.name!=='string'||b.name.length>40)throw Error('Объект выходит за разрешённые размеры.');return {x:b.x,z:b.z,w:b.w,d:b.d,h:b.h,color:Math.round(b.color),name:b.name,roof:b.roof!==false};};
 const clean=emptyCity();if(data.graffiti!=null){if(typeof data.graffiti!=='string'||data.graffiti.length>750000||!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(data.graffiti))throw Error('Граффити должно быть PNG не больше 750 КБ.');clean.graffiti=data.graffiti;}for(const [id,b] of Object.entries(data.overrides)){if(!/^\d{1,3}$/.test(id))throw Error('Неверный номер дома.');clean.overrides[id]=check(b);}clean.added=data.added.map(check);
 clean.trees=data.trees.map(p=>{if(!Number.isFinite(p.x)||!Number.isFinite(p.z)||Math.abs(p.x)>84||Math.abs(p.z)>29)throw Error('Неверное место дерева.');return {x:p.x,z:p.z};});
 for(const key of ['hello','place']){if(typeof data.replies[key]!=='string'||data.replies[key].length>400)throw Error('Реплика должна быть не длиннее 400 букв.');clean.replies[key]=data.replies[key];}if(data.profiles){if(!Array.isArray(data.profiles)||data.profiles.length!==4)throw Error('Нужны четыре набора реплик.');clean.profiles=data.profiles.map((p,i)=>{if(typeof p.hello!=='string'||typeof p.place!=='string'||p.hello.length>400||p.place.length>400)throw Error('Слишком длинная реплика.');return {name:residentProfiles[i].name,hello:p.hello,place:p.place};});}if(data.rooms){if(typeof data.rooms!=='object'||Array.isArray(data.rooms)||Object.keys(data.rooms).length>160)throw Error('Неверный список комнат.');for(const [id,room] of Object.entries(data.rooms)){if(!/^\d{1,3}$/.test(id))throw Error('Неверный номер комнаты.');clean.rooms[id]=validateRoom(room);}}return clean;
}
export function loadCity(){try{return validateCity(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch{return emptyCity()}}
export function saveCity(data){const clean=validateCity(data);localStorage.setItem(STORAGE_KEY,JSON.stringify(clean));return clean;}
export function onReservedPath(x,z,w=0,d=0){
 const intersects=(cx,cz,cw,cd)=>Math.abs(x-cx)<(w+cw)/2+.35&&Math.abs(z-cz)<(d+cd)/2+.35;
 return intersects(0,17.5,162,9.8)||intersects(0,-17.5,162,9.8)||intersects(-56,0,7,41)||intersects(23,0,7,41);
}

export const GARAGE_KEY='mark-next-city-garage-v1';
export const carOffers=[{id:'yellow',name:'Жёлтая машина',price:450,color:0xe4c857},{id:'blue',name:'Синяя машина',price:600,color:0x609bbd},{id:'red',name:'Красная машина',price:650,color:0xd98172}];
export function loadGarage(){try{const p=JSON.parse(localStorage.getItem(GARAGE_KEY));if(!Number.isFinite(p.balance)||p.balance<0||p.balance>1000)throw Error();if(p.car&&!carOffers.some(c=>c.id===p.car))throw Error();return {balance:p.balance,car:p.car||null,x:Number.isFinite(p.x)&&Math.abs(p.x)<80?p.x:41,z:Number.isFinite(p.z)&&Math.abs(p.z)<21?p.z:15.3};}catch{return {balance:1000,car:null,x:41,z:15.3}}}
export function buyCar(garage,id){if(garage.car)return garage;const offer=carOffers.find(c=>c.id===id);if(!offer||garage.balance<offer.price)throw Error('Не хватает игровых монет.');return {...garage,balance:garage.balance-offer.price,car:id,x:41,z:15.3};}
export function saveGarage(garage){localStorage.setItem(GARAGE_KEY,JSON.stringify(garage));}
export const defaultRoom=()=>({wall:0xe8dbc0,floor:0xd6bf8f,furniture:[{type:'sofa',x:-3,z:-2,color:0x7ca398},{type:'table',x:1,z:-1,color:0xc5a16b},{type:'cabinet',x:4,z:-4,color:0xb6a1bf}]});
export const furnitureSizes={sofa:{w:2.6,d:2,h:.7},table:{w:2,d:1.4,h:.7},cabinet:{w:1.4,d:1.4,h:2.2}};
export function validateRoom(room){if(!room||!Number.isInteger(room.wall)||!Number.isInteger(room.floor)||room.wall<0||room.wall>0xffffff||room.floor<0||room.floor>0xffffff||!Array.isArray(room.furniture)||room.furniture.length>12)throw Error('Неверные данные комнаты.');const furniture=room.furniture.map((f,i)=>{const size=furnitureSizes[f.type];if(!size||!Number.isFinite(f.x)||!Number.isFinite(f.z)||Math.abs(f.x)+size.w/2>6.5||Math.abs(f.z)+size.d/2>6.5||!Number.isInteger(f.color)||f.color<0||f.color>0xffffff)throw Error('Мебель должна оставаться внутри комнаты.');if(Math.abs(f.x)<1.8+size.w/2&&f.z+size.d/2>3)throw Error('Оставь свободным проход к выходу.');if(room.furniture.slice(0,i).some(o=>Math.abs(o.x-f.x)<(furnitureSizes[o.type].w+size.w)/2+.15&&Math.abs(o.z-f.z)<(furnitureSizes[o.type].d+size.d)/2+.15))throw Error('Предметы мебели не должны накладываться.');return {type:f.type,x:f.x,z:f.z,color:f.color};});return {wall:room.wall,floor:room.floor,furniture};}
