const q=(skill,title,art,question,answers,correct,hint,explanation)=>({skill,title,art,question,answers,correct,hint,explanation});
export const CHAPTERS=[
 {title:'The missing word',place:'Juana Briones School',x:41,z:1.1,friend:'Abir',color:0xffd05c,puzzles:[
 q('REBUS · WORDPLAY','A little perspective','STAND\n   I','Read the position of I and STAND. Which word does this picture suggest?',['Outstanding','Understand','Standing tall','I stand'],1,'Say where I am: I am ___ STAND.','I is UNDER the word STAND. Put UNDER and STAND together: UNDERSTAND. Position can carry meaning!'),
 q('PATTERNS · REASONING','The classroom code','3 → 7 → 15 → 31 → ?','Each number follows the same two-step rule. What comes next?',['47','62','63','64'],2,'Double each number, then add one. Check that rule on every pair.','3 × 2 + 1 = 7. Then 7 × 2 + 1 = 15. The same rule gives 31 × 2 + 1 = 63.'),
 q('LOGIC · PLANNING','The team schedule','READ → DRAW → BUILD','Abir reads before Mark draws. Koki builds after Mark draws. Each activity takes 15 minutes. Starting at 3:10, when does building finish?',['3:40','3:45','3:55','4:10'],2,'There are three activities in sequence, not at the same time.','Three 15-minute activities take 45 minutes. 3:10 + 45 minutes = 3:55. Planning means noticing dependencies.') ]},
 {title:'The pearl equation',place:'Boba Lab',x:-38,z:.1,friend:'Koki',color:0xb097ef,puzzles:[
 q('FRACTIONS · PROPORTIONS','Mix it right','MILK  3 : 1  TEA','A pretend recipe uses 3 parts milk to 1 part tea. For 400 mL total, how much tea do you need?',['100 mL','133 mL','200 mL','300 mL'],0,'There are 3 + 1 equal parts in total.','400 ÷ 4 = 100 mL per part. Tea is one part, so 100 mL tea and 300 mL milk make 400 mL.'),
 q('REBUS · VOCABULARY','A cup-sized clue','T  +  EAM','Say the letter out loud, then join it to EAM. What do you get?',['Steam','Team','Time','Cream'],1,'The name of the letter T sounds like “tea.”','T + EAM spells TEAM. A good team shares ideas and checks its reasoning.'),
 q('FRACTIONS · COMPARISON','Share the pearls','MARK: ⅜    KOKI: ¼','Mark uses 3/8 of a bag of pretend pearls. Koki uses 1/4 of the same bag. What fraction remains?',['1/8','3/8','1/2','5/8'],1,'Change 1/4 into eighths before adding.','1/4 = 2/8. Together they use 3/8 + 2/8 = 5/8. The remaining fraction is 8/8 − 5/8 = 3/8.') ]},
 {title:'A super-smart shop',place:"Trader Joe’s",x:-46,z:13.6,friend:'Egor',color:0xe96b70,puzzles:[
 q('MONEY · DECIMALS','The picnic budget','$20.00\n$3.50 + $4.25 + $2.75','Your fictional shopping list is fruit $3.50, bread $4.25, and cheese $2.75. What change do you get from $20? Ignore tax.',['$8.50','$9.50','$10.50','$11.50'],1,'Add $4.25 and $2.75 first; they make a whole number.','$4.25 + $2.75 = $7.00. Add $3.50: total $10.50. $20.00 − $10.50 = $9.50 change.'),
 q('UNIT PRICE · COMPARISON','Which pack wins?','6 FOR $3  /  10 FOR $4','Two fictional packs contain identical apples. Which has the lower price per apple?',['6-pack: 50¢ each','10-pack: 40¢ each','They cost the same','Not enough information'],1,'Divide the price by the number of apples.','$3 ÷ 6 = $0.50 each. $4 ÷ 10 = $0.40 each. The 10-pack is cheaper per apple, though you should still buy only what you need.'),
 q('LOGIC · ELIMINATION','The mystery bag','APPLE • CARROT • BREAD','Egor chose one item. It grows underground and is not a fruit. What is in the bag?',['Apple','Carrot','Bread','All three'],1,'Both clues must be true for the same item.','A carrot is a root that grows underground. An apple grows on a tree, and bread is made from ingredients. Check every clue, not just one.') ]},
 {title:'The diamond code',place:'Baseball Park',x:-30,z:1,friend:'Koki',color:0x72bea7,puzzles:[
 q('DATA · ARITHMETIC','Read the scoreboard','INNING   1  2  3  4\nHOME     2  0  3  1\nAWAY     1  2  0  2','After four innings, how many runs ahead is the home team?',['1','2','3','Tie'],0,'Add each row separately, then compare the totals.','Home: 2 + 0 + 3 + 1 = 6. Away: 1 + 2 + 0 + 2 = 5. Home leads by 1 run.'),
 q('FRACTIONS · PERCENTAGES','Practice pays off','8 HITS / 20 ATTEMPTS','In a batting practice challenge, Mark hits 8 of 20 pitches. What percentage is that?',['20%','25%','40%','80%'],2,'Make the denominator 100 by multiplying both numbers by 5.','8/20 = 40/100 = 40%. This describes this practice session; it is not an official batting average.'),
 q('REBUS · WORDPLAY','Name that moment','HOME\n🏃','A runner appears beneath the word HOME. Which baseball phrase does the picture suggest?',['Fly ball','Home run','Double play','Strike out'],1,'Combine the word with what the person is doing.','HOME + RUN gives HOME RUN. Rebus puzzles combine pictures, words and positions to express an idea.') ]},
 {title:'Between the lines',place:'City Library',x:78,z:12.1,friend:'Josie',color:0x67bad8,puzzles:[
 q('REBUS · SPATIAL READING','A hidden message','LINE\nREAD\nLINE','What phrase is shown by the position of READ?',['Read aloud','Read between the lines','Read the room','Read backwards'],1,'Where is READ compared with the two LINEs?','READ is BETWEEN two LINEs: “read between the lines.” It means looking for meaning that is implied rather than stated.'),
 q('READING · INFERENCE','The wet umbrella','CLUE FILE  /  04','Josie enters the library carrying a wet umbrella. Her shoes leave small wet prints. What is the best-supported explanation?',['It is probably wet outside','The library roof is broken','Josie went swimming','Every book is wet'],0,'Choose the answer supported by both details without inventing extra facts.','The umbrella and wet shoes suggest wet weather outside. “Probably” matters: the clues support an inference, not absolute certainty.'),
 q('CODES · SPELLING','The comic shelf cipher','4 · 15 · 7 / 13 · 1 · 14','Use A=1, B=2, C=3, and so on. Josie encoded the name of Mark’s favorite comic. What does it say?',['BAT MAN','DOG MAN','CAT KID','BIG NATE'],1,'The first three letters are D, O, G. Decode the second group too.','4=D, 15=O, 7=G, 13=M, 1=A, 14=N: DOG MAN! Dav Pilkey’s comic lives on our imaginary library shelf. A code uses a consistent rule to represent information.') ]},
 {title:'A table for the team',place:'Neighborhood Food Court',x:-65,z:-1.4,friend:'Egor & Josie',color:0xf49b57,puzzles:[
 q('BEVRI · FRACTIONS','Share the khachapuri','12 EQUAL PIECES / 5 FRIENDS','In our pretend Bevrі picnic, Mark, Abir, Koki, Egor and Josie each eat 2 of 12 equal pieces of khachapuri. What fraction remains?',['1/12','1/6','1/3','5/6'],1,'Five friends eat 5 × 2 pieces. Simplify the fraction left.','5 × 2 = 10 pieces eaten. 12 − 10 = 2 remain. 2/12 simplifies to 1/6. These are fictional portions for the puzzle.'),
 q('DENNY’S · VALUE','Breakfast detective','A: $7 + $3\nB: $12 − $3','Fictional breakfast A costs $7 plus a $3 drink. Breakfast B costs $12 with a $3 coupon. Which is cheaper, before tax and tip?',['A by $1','B by $1','Same price','B by $3'],1,'Find each final price before comparing.','A costs $10. B costs $9 after the coupon. B is cheaper by $1. These are made-up puzzle prices, not restaurant prices.'),
 q('CHIPOTLE · LOGIC','The perfect order','BEANS ✓  /  RICE ✓  /  NO CORN','Abir wants beans and rice, but no corn. Which fictional bowl matches every clue?',['Rice, beans, corn','Rice, chicken, salsa','Rice, beans, salsa','Beans, lettuce, corn'],2,'Cross out any bowl with corn, then check for both required ingredients.','Rice, beans and salsa includes both requested ingredients and no corn. Checking all constraints is a useful skill in everyday decisions and programming.') ]}
];
export const TOTAL=CHAPTERS.reduce((n,c)=>n+c.puzzles.length,0);
export const QUEST_KEY='mark-comics-learning-v1';
export function loadProgress(storage){try{const n=JSON.parse(storage.getItem(QUEST_KEY));return Number.isInteger(n)&&n>=0&&n<=TOTAL?n:0;}catch{return 0;}}
export function currentMission(progress){return CHAPTERS[Math.floor(progress/3)]||null;}
export function canCollect(progress,position,inside){const c=currentMission(progress);return !!c&&!inside&&Math.hypot(position.x-c.x,position.z-c.z)<2.4;}
export function saveProgress(storage,index){try{storage.setItem(QUEST_KEY,JSON.stringify(index));return true;}catch{return false;}}
export function checkAnswer(puzzle,index){return Number.isInteger(index)&&index===puzzle.correct;}
