export function setupConcert({$,pause,resume,travel,reward}){
 const patterns=[[0,1,0,2],[2,0,3,1,2],[0,2,1,3,2,0]];
 let round=0,at=0,playing=false,timers=[],audio=null,won=false;
 const pads=[...document.querySelectorAll('[data-note]')];
 function tone(note){try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.type='triangle';oscillator.frequency.value=[261.63,329.63,392,523.25][note];gain.gain.setValueAtTime(.0001,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.13,audio.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.3);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start();oscillator.stop(audio.currentTime+.32);}catch{}}
 function flash(note){tone(note);pads[note].classList.add('lit');timers.push(setTimeout(()=>pads[note].classList.remove('lit'),280));}
 function stop(){timers.forEach(clearTimeout);timers=[];playing=false;pads.forEach(p=>{p.classList.remove('lit');p.disabled=false;});audio?.suspend();}
 function play(){stop();at=0;playing=true;$('rhythmStatus').textContent='Watch and listen…';pads.forEach(p=>p.disabled=true);patterns[round].forEach((n,i)=>timers.push(setTimeout(()=>flash(n),350+i*520)));timers.push(setTimeout(()=>{playing=false;pads.forEach(p=>p.disabled=false);$('rhythmStatus').textContent='Your turn! Repeat the color pattern. No time limit.';},350+patterns[round].length*520));}
 pads.forEach((p,i)=>p.onclick=()=>{if(playing)return;flash(i);if(i!==patterns[round][at]){at=0;$('rhythmStatus').textContent='Try again! Press Replay pattern to hear the clue again.';return;}at++;if(at===patterns[round].length){if(round===2){if(!won){reward();won=true;}$('rhythmStatus').textContent='ENCORE! All three patterns solved. You earned 30 sparks!';at=0;}else{round++;at=0;$('rhythmStatus').textContent='Great listening! Press Replay pattern for round '+(round+1)+'.';}}});
 $('concertButton').onclick=()=>{travel();pause();$('concert').showModal();$('rhythmStatus').textContent='Press Replay pattern, then repeat the notes. Sound is optional — follow the lights.';};$('playPattern').onclick=play;$('closeConcert').onclick=()=>{stop();$('concert').close();resume();};$('concert').addEventListener('cancel',()=>{stop();resume();});
}
export function drawConcert(ctx,time,ground){const x=8500;ctx.save();ctx.translate(x,ground);ctx.fillStyle='#182239';ctx.fillRect(-250,-270,500,270);ctx.fillStyle='#613e77';ctx.fillRect(-230,-247,460,222);for(let i=0;i<5;i++){ctx.fillStyle=['#ffdb6c44','#77e4dc44','#eb729344'][i%3];ctx.beginPath();ctx.moveTo(-190+i*95,-250);ctx.lineTo(-270+i*100+Math.sin(time+i)*45,-25);ctx.lineTo(-70+i*100+Math.sin(time+i)*45,-25);ctx.fill();}ctx.fillStyle='#ffd66d';ctx.font='900 52px Arial';ctx.textAlign='center';ctx.fillText('AJR',0,-177);ctx.font='bold 11px Arial';ctx.fillStyle='#fff5df';ctx.fillText('MARK CITY • IMAGINARY CONCERT',0,-153);for(let i=0;i<3;i++){const px=(i-1)*110,py=-70+Math.sin(time*4+i)*5;ctx.fillStyle='#172437';ctx.beginPath();ctx.arc(px,py-39,13,0,7);ctx.fill();ctx.fillStyle=['#ecc46c','#65bbba','#e67987'][i];ctx.fillRect(px-15,py-25,30,42);ctx.strokeStyle='#101929';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(px-8,py+14);ctx.lineTo(px-13,-17);ctx.moveTo(px+8,py+14);ctx.lineTo(px+14,-17);ctx.stroke();if(i===0){ctx.fillStyle='#cf8157';ctx.beginPath();ctx.ellipse(px,py,24,16,-.5,0,7);ctx.fill();}if(i===1){ctx.strokeStyle='#eee';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(px+22,-20);ctx.lineTo(px+22,py-28);ctx.stroke();}if(i===2){ctx.fillStyle='#262a41';ctx.fillRect(px-35,py,70,14);}}ctx.fillStyle='#f0cb70';ctx.fillRect(-260,-13,520,13);ctx.textAlign='left';ctx.restore();}
