const episodes=[
 {name:'Mom · Bike practice',tag:'BALANCE & SAFE CHOICES',art:'🚲',intro:'Mom, a tall brunette, steadies your bicycle. “Eyes ahead, hands on the handlebars. Let’s practice in a quiet place together.”',question:'Before starting, what is the best plan?',answers:['Put on a fitted helmet and check the brakes with Mom','Race down the hill without checking','Look at a phone while riding'],correct:0,explain:'A helmet, working brakes and a quiet practice area help you learn safely. Mom walks beside you while you practice balancing.',action:'Practice balancing',kind:'bike'},
 {name:'Dad · School on time',tag:'TIME & PLANNING',art:'◷',intro:'Dad is tall and has a moustache. “School starts at 8:15. We need 12 minutes to travel and 5 minutes to lock the bike and walk in.”',question:'What is the latest time to leave and still arrive at 8:15?',answers:['8:03','7:58','8:10'],correct:1,explain:'12 + 5 = 17 minutes. 8:15 minus 17 minutes is 7:58. Leaving a little earlier gives you a useful buffer.',action:null},
 {name:'Veronika · Art club',tag:'CREATIVITY & FRIENDSHIP',art:'🎨',intro:'Veronika is in another class at school, but you go to art together. Today she has playfully swapped the paint labels. “Can you solve my color mystery?”',question:'With ordinary red, yellow and blue paints, which pair would you try to mix a green?',answers:['Red + yellow','Blue + red','Yellow + blue'],correct:2,explain:'Yellow and blue paints can mix a green. Try small amounts first: different pigments make different shades. Veronika laughs and helps put the labels back.',action:null},
 {name:'Olena · A quiet room',tag:'FEELINGS & ASKING FOR HELP',art:'♡',intro:'Olena, the school psychologist, welcomes you into a quiet room with plants, cushions and drawing paper. “Every feeling is welcome here.”',question:'Mark feels frustrated by a hard puzzle. Which response could help him?',answers:['“I must never make a mistake.”','“I feel frustrated. Can I take a break and ask for a hint?”','“I should hide how I feel.”'],correct:1,explain:'You can name a feeling, take a break and ask a trusted person for help. A mistake is information, not a judgment about you. Olena is a fictional character in this game.',action:null}
];
export function setupEpisodes({pause,resume}){
 const b=document.createElement('button');b.id='episodesButton';b.textContent='Friends & family';document.querySelector('.header-links').prepend(b);
 const d=document.createElement('dialog');d.id='episodes';d.innerHTML='<div class="puzzle-header"><span class="eyebrow">LITTLE EVERYDAY ADVENTURES</span><button id="closeEpisodes" aria-label="Close family episodes">×</button></div><h2>People who make a city.</h2><nav id="episodeTabs"></nav><div id="episodeScene"></div><h3 id="episodeTitle"></h3><p id="episodeIntro"></p><p id="episodeQuestion"></p><div id="episodeAnswers"></div><p id="episodeFeedback" role="status"></p><button id="bikePractice" hidden>Practice balancing</button><div id="bikePanel" hidden><p>Keep the bicycle near the center. Use ← / → or the buttons for 8 seconds. No penalty — try again whenever you like.</p><div id="balanceTrack"><span id="bikeRider">🚲</span><i></i></div><button id="bikeLeft">← Lean left</button><button id="bikeRight">Lean right →</button><button id="startBike">Start practice</button><p id="bikeResult" role="status"></p></div>';document.body.appendChild(d);const $=id=>document.getElementById(id);let running=false,pos=0,elapsed=0,timer=null;
 const stop=()=>{running=false;clearInterval(timer);};
 function select(i){stop();const e=episodes[i];$('episodeTitle').textContent=e.name;$('episodeIntro').textContent=e.intro;$('episodeQuestion').textContent=e.question;$('episodeFeedback').textContent='';$('episodeScene').textContent=e.art;$('episodeAnswers').replaceChildren();$('bikePractice').hidden=true;$('bikePanel').hidden=true;e.answers.forEach((text,n)=>{const answer=document.createElement('button');answer.textContent=text;answer.onclick=()=>{if(n===e.correct){$('episodeFeedback').textContent=e.explain;$('bikePractice').hidden=e.kind!=='bike';}else $('episodeFeedback').textContent='Think about all the details and try another idea. You can take your time.';};$('episodeAnswers').appendChild(answer);});}
 episodes.forEach((e,i)=>{const tab=document.createElement('button');tab.textContent=e.name.split(' · ')[0];tab.onclick=()=>select(i);$('episodeTabs').appendChild(tab);});
 b.onclick=()=>{pause();select(0);d.showModal();};$('closeEpisodes').onclick=()=>{stop();d.close();resume();};d.addEventListener('cancel',()=>{stop();resume();});$('bikePractice').onclick=()=>{$('bikePanel').hidden=false;};const lean=n=>{if(running)pos=Math.max(-1,Math.min(1,pos+n*.14));};$('bikeLeft').onclick=()=>lean(-1);$('bikeRight').onclick=()=>lean(1);d.addEventListener('keydown',e=>{if(running&&['ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();e.stopPropagation();lean(e.code==='ArrowLeft'?-1:1);}});$('startBike').onclick=()=>{stop();pos=0;elapsed=0;running=true;$('bikeResult').textContent='Mom is right beside you. Keep it steady!';timer=setInterval(()=>{elapsed+=.1;pos+=Math.sin(elapsed*2)*.025+.008;$('bikeRider').style.left=(50+pos*42)+'%';if(Math.abs(pos)>1){stop();$('bikeResult').textContent='Mom steadies the bike. Try small adjustments and start again!';}else if(elapsed>=8){stop();$('bikeResult').textContent='You did it! Eight seconds of balanced riding. Mom is cheering!';}},100);};
}
